name: Build Cemu

on:
  push:
  workflow_call:
    inputs:
      deploymode:
        required: false
        type: string

env:
  VCPKG_ROOT: "${{github.workspace}}/dependencies/vcpkg"
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

jobs:
  build-android:
    runs-on: ubuntu-latest
    container:
      image: cimg/android:2025.09

    steps:
      - name: Install system dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y gettext mono-complete ninja-build automake libtool
      
      - name: Checkout Upstream Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Uncompile message catalogs
        run: |
          for mo_file in bin/resources/*/cemu.mo
          do
            echo $mo_file
            language_code=$(basename $(dirname $mo_file))
            po_file=src/android/app/src/main/assets/translations/$language_code/cemu.po
            mkdir -p $(dirname $po_file)
            msgunfmt $mo_file -o $po_file || echo "Failed to uncompile message catalog from $mo_file"
          done
      
      - name: "Bootstrap vcpkg"
        run: |
          bash ./dependencies/vcpkg/bootstrap-vcpkg.sh
        
      - name: 'Setup NuGet Credentials for vcpkg'
        shell: 'bash'
        run: |
          mono `./dependencies/vcpkg/vcpkg fetch nuget | tail -n 1` \
          sources add \
          -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
          -storepasswordincleartext \
          -name "GitHub" \
          -username "${{ github.repository_owner }}" \
          -password "${{ secrets.GITHUB_TOKEN }}"
          mono `./dependencies/vcpkg/vcpkg fetch nuget | tail -n 1` \
          setapikey "${{ secrets.GITHUB_TOKEN }}" \
          -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Fixes (Android)
        run: |
          echo "Android Fixes"
          #sed -i -e 's|compileSdk = 36|compileSdk = 31|g;s|minSdk = 31|minSdk = 21|g;s|targetSdk = 35|targetSdk = 30|g' src/android/app/build.gradle.kts
          #cp ci/AndroidManifest.xml src/android/app/src/main/AndroidManifest.xml
          #cat src/android/app/src/main/AndroidManifest.xml
          
      - name: Build Cemu
        run: |
          cd ./src/android
          ./gradlew assembleRelease
          ./gradlew testRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cemu-bin-android
          path: ./src/android/app/build/outputs/apk/*/*.apk
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cemu-bin-android
          path: ./src/android/app/build/outputs/apk/*/*.apk
