name: Build Cemu

on:
  push:
    paths-ignore:
      - "*.md"
  workflow_call:
    inputs:
      deploymode:
        required: false
        type: string

jobs:    
  build-appimage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Upstream Repo
      uses: actions/checkout@v3
      with:
        repository: cemu-project/Cemu
        ref: main
        submodules: true
    - name: Checkout AppImage Repo
      uses: actions/checkout@v3
      with:
        repository: qurious-pixel/Cemu
        ref: ci-appimage
        clean: false
        path: ci

    - name: cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.ccache
        key: build-${{github.run_id}}
        restore-keys: |
          build

    - name: Get Cemu release version
      run: |
        gcc -o getversion .github/getversion.cpp
        echo "Cemu CI version: $(./getversion)"
        echo "CEMU_FOLDER_NAME=Cemu_$(./getversion)" >> $GITHUB_ENV
        echo "CEMU_VERSION=$(./getversion)" >> $GITHUB_ENV

    - name: "Temp Fixes"
      run: |
        cat > dist/linux/docker.sh << EOF
        #!/bin/bash -ex
        yum install -y vulkan-devel libglvnd-devel       
        cmake -S . -B build -DCMAKE_BUILD_TYPE=release -DENABLE_VCPKG=OFF -DPORTABLE=OFF -DCMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE=OFF -G Ninja
        cmake --build build
        mv bin/Cemu_release bin/Cemu
        dist/linux/appimage.sh
        EOF
    - name: "Temp Fixes"
      run: |
        echo "Linux Fixes"
        cp ci/scripts/appimage.sh dist/linux/
        cp ci/scripts/cemu.png dist/linux/info.cemu.Cemu.png
        ls -al dist/linux/
        chmod +x dist/linux/{appimage.sh,docker.sh}
            
    - name: "Build Cemu"
      run: |
          docker pull quriouspixel/cemu
          docker run -u root -e VERSION=${{ env.CEMU_VERSION }} -v $(pwd):/Cemu -v "$HOME/.ccache":/root/.ccache -w /Cemu quriouspixel/cemu /bin/bash dist/linux/docker.sh

    - name: "Build AppImage"
      run: |
        ls -al artifacts
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: cemu-appimage-x64
        path: artifacts
