name: Build Cemu

on:
  workflow_call:
  push:

env:
  VCPKG_ROOT: "${{github.workspace}}/dependencies/vcpkg"
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'
  VCPKG_FORCE_DOWNLOADED_BINARIES: true
  
jobs:
  build-windows:
    runs-on: windows-2022
    steps:
    - name: "Checkout repo"
      uses: actions/checkout@v4
      with:
        submodules: "recursive"

    - name: Setup release mode parameters
      run: |
        echo "BUILD_MODE=release" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        echo "BUILD_FLAGS=-DCMAKE_SYSTEM_NAME=Windows -DCMAKE_PREFIX_PATH=D:\a\_temp\msys64/ucrt64 -DIH264D_ARCHITECTURE=x86_64 -DENABLE_VCPKG=OFF -DENABLE_DISCORD_RPC=OFF -GNinja" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        echo "Build mode is release"

    - uses: msys2/setup-msys2@v2
      if: false
      id: msys2
    - env:
        MSYS2_LOCATION: ${{ steps.msys2.outputs.msys2-location }}
      run: echo "$env:MSYS2_LOCATION"
      
    - name: Setup msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        cache: true
        install: |
          mingw-w64-ucrt-x86_64-clang
          mingw-w64-ucrt-x86_64-ccache
          mingw-w64-ucrt-x86_64-cmake
          mingw-w64-ucrt-x86_64-lld
          mingw-w64-ucrt-x86_64-ninja
          mingw-w64-ucrt-x86_64-SDL2
          mingw-w64-ucrt-x86_64-pugixml
          mingw-w64-ucrt-x86_64-rapidjson
          mingw-w64-ucrt-x86_64-boost
          mingw-w64-ucrt-x86_64-libzip
          mingw-w64-ucrt-x86_64-glslang
          mingw-w64-ucrt-x86_64-glm
          mingw-w64-ucrt-x86_64-cc
          mingw-w64-ucrt-x86_64-gcc
          mingw-w64-ucrt-x86_64-libpng
          mingw-w64-ucrt-x86_64-pkgconf
          mingw-w64-ucrt-x86_64-wxwidgets3.3-common
          mingw-w64-ucrt-x86_64-wxwidgets3.3-common-libs
          mingw-w64-ucrt-x86_64-wxwidgets3.3-gtk3
          mingw-w64-ucrt-x86_64-wxwidgets3.3-gtk3-libs
          mingw-w64-ucrt-x86_64-wxwidgets3.3-msw
          mingw-w64-ucrt-x86_64-wxwidgets3.3-msw-cb_headers
          mingw-w64-ucrt-x86_64-wxwidgets3.3-msw-libs
          mingw-w64-ucrt-x86_64-hidapi
          mingw-w64-ucrt-x86_64-libtiff
          mingw-w64-ucrt-x86_64-libusb
          base-devel
          curl
          git
          zlib
          zstd
          openssl
          fmt
  
    - name: "Bootstrap vcpkg"
      run: |
        ./dependencies/vcpkg/bootstrap-vcpkg.bat

    - name: 'Setup NuGet Credentials for vcpkg'
      shell: 'bash'
      run: |
        `./dependencies/vcpkg/vcpkg.exe fetch nuget | tail -n 1` \
        sources add \
        -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
        -storepasswordincleartext \
        -name "GitHub" \
        -username "${{ github.repository_owner }}" \
        -password "${{ secrets.GITHUB_TOKEN }}"
        `./dependencies/vcpkg/vcpkg.exe fetch nuget | tail -n 1` \
        setapikey "${{ secrets.GITHUB_TOKEN }}" \
        -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    - name: "cmake"
      run: |
        mkdir -p build
        cd build
        echo "[INFO] BUILD_FLAGS: ${{ env.BUILD_FLAGS }}"
        echo "[INFO] BUILD_MODE: ${{ env.BUILD_MODE }}"
        cmake .. ${{ env.BUILD_FLAGS }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_MODE }} -DVCPKG_INSTALL_OPTIONS="--clean-after-build"

    - name: "Build Cemu"
      run: |
        cd build
        cmake --build . --config ${{ env.BUILD_MODE }}

    - name: Prepare artifact
      run: Rename-Item bin/Cemu_release.exe Cemu.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cemu-bin-windows-x64
        path: ./bin/Cemu.exe

