name: Build Cemu

on:
  workflow_dispatch:
  push:

env:
  VCPKG_ROOT: "${{github.workspace}}/dependencies/vcpkg"
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

jobs:
  build-cemu:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
    - name: Setup dependencies
      run: |
        sudo dnf install -y bison bluez-libs-devel clang cmake cubeb-devel findutils freeglut-devel git glm-devel gtk3-devel kernel-headers libgcrypt-devel libsecret-devel libtool libudev-devel libusb1-devel mono-complete nasm ninja-build python3-pip perl-open perl-FindBin perl-File-Compare perl-File-Copy perl-IPC-Cmd rsync systemd-devel vcpkg vim-enhanced wayland-protocols-devel wget zip zlib-devel zlib-ng-compat-static
        pip3 install jinja2 passlib
        git config --global --add safe.directory '*'

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: "recursive"
        fetch-depth: 0

    - name: Setup release mode parameters
      run: |
        echo "BUILD_MODE=release" >> $GITHUB_ENV
        echo "BUILD_FLAGS=" >> $GITHUB_ENV
        echo "Build mode is release"

    - name: "Fetch full history for vcpkg submodule"
      run: |
        cd dependencies/vcpkg
        git remote update
        git pull origin master
        
    - name: "Bootstrap vcpkg"
      run: |
        bash ./dependencies/vcpkg/bootstrap-vcpkg.sh
        
    - name: "cmake"
      run: |
        cmake -S . -B build ${{ env.BUILD_FLAGS }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_MODE }} -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -G Ninja -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_AR=/usr/bin/ar
        
    - name: "Build Cemu"
      run: |
        cmake --build build
        
    - name: Prepare artifact
      run: mv bin/Cemu_release bin/Cemu
              
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cemu-bin-linux-x64
        path: ./bin/Cemu


              
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cemu-bin-macos-${{ matrix.arch }}
        path: ./bin/Cemu.dmg
