name: Build Cemu

on:
  workflow_dispatch:
  push:

jobs:
  build-cemu:
    runs-on: ubuntu-latest
    container:
      image: cachyos/cachyos
    steps:
    - name: Setup dependencies
      run: |
        sudo pacman -Syu --noconfirm
        sudo pacman -S --noconfirm --needed base-devel bluez-libs clang cmake freeglut git glm gtk3 libgcrypt libpulse libsecret linux-headers llvm nasm ninja systemd unzip zip
        git config --global --add safe.directory '*'

    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: cemu-project/Cemu
        ref: main
        submodules: recursive

    - name: "Fetch full history for vcpkg submodule"
      run: |
        cd dependencies/vcpkg
        git fetch --unshallow
        git pull --all
        
    - name: "cmake"
      run: |
        cmake -S . -B build ${{ env.BUILD_FLAGS }} -DCMAKE_BUILD_TYPE=release -DVCPKG_BUILD_TYPE=release -DPORTABLE=OFF -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ -G Ninja -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja
        
    - name: "Build Cemu"
      run: |
        cmake --build build
        
    - name: Prepare artifact
      run: mv bin/Cemu_release bin/Cemu
              
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cemu-bin-linux-x64
        path: ./bin/Cemu

