name: Build Cemu

on:
  pull_request_target:
    paths-ignore:
      - "*.md"
    types:
      - opened
      - synchronize
      - reopened
  push:
    paths-ignore:
      - "*.md"
  workflow_call:
    inputs:
      deploymode:
        required: false
        type: string

env:
  VCPKG_ROOT: "${{github.workspace}}/dependencies/vcpkg"
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

jobs:
  build-ubuntu:
    runs-on: ubuntu-22.04
    env:
      CACHEDIR: ~/.ccache
    steps:
    - name: Checkout Upstream Repo
      uses: actions/checkout@v4
      with:
        repository: capitalistspz/Cemu # cemu-project/Cemu # 
        ref: wiimote-ext-strict # camera # main
        submodules: recursive

    - name: cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.ccache
        key: build-${{github.run_id}}
        restore-keys: |
          build

    - name: Setup release mode parameters (for deploy)
      #if: ${{ inputs.deploymode == 'release' }}
      run: |
        echo "BUILD_MODE=release" >> $GITHUB_ENV
        echo "BUILD_FLAGS=" >> $GITHUB_ENV
        echo "Build mode is release"

    #- name: Setup debug mode parameters (for continous build)
    #  if: ${{ inputs.deploymode != 'release' }}
    #  run: |
    #    echo "BUILD_MODE=debug" >> $GITHUB_ENV
    #    echo "BUILD_FLAGS=" >> $GITHUB_ENV
    #    echo "Build mode is debug"
        
    - name: "Install system dependencies"
      run: |
        sudo apt update -qq
        sudo apt install -y clang-15 cmake freeglut3-dev libgcrypt20-dev libglm-dev libgtk-3-dev libpulse-dev libsecret-1-dev libsystemd-dev libudev-dev nasm ninja-build libbluetooth-dev ccache

    - name: "Setup cmake"
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.29.0'
        
    - name: "Create cache dir"
      run: |
        if [[ ! -e ${{ env.CACHEDIR }} ]]; then mkdir ${{ env.CACHEDIR }}; fi
        ls -al ${{ env.CACHEDIR }}

    - name: "Linux Fixes"
      run: |
        echo "Linux Fixes"

    - name: "Fetch full history for vcpkg submodule"
      run: |
        cd dependencies/vcpkg
        git fetch --unshallow
        git checkout 431eb6bda0950874c8d4ed929cc66e15d8aae46f
        
    - name: "Bootstrap vcpkg"
      run: |
        bash ./dependencies/vcpkg/bootstrap-vcpkg.sh
        
    - name: 'Setup NuGet Credentials for vcpkg'
      shell: 'bash'
      run: |
        mono `./dependencies/vcpkg/vcpkg fetch nuget | tail -n 1` \
        sources add \
        -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
        -storepasswordincleartext \
        -name "GitHub" \
        -username "${{ github.repository_owner }}" \
        -password "${{ secrets.GITHUB_TOKEN }}"
        mono `./dependencies/vcpkg/vcpkg fetch nuget | tail -n 1` \
        setapikey "${{ secrets.GITHUB_TOKEN }}" \
        -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        
    - name: "cmake"
      run: |
        cmake -S . -B build  ${{ env.BUILD_FLAGS }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_MODE }} -DPORTABLE=OFF -DCMAKE_C_COMPILER=/usr/bin/clang-15 -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER=/usr/bin/clang++-15 -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -G Ninja
    - name: "Build Cemu"
      run: |
        cmake --build build
        mv bin/Cemu_release bin/Cemu
               
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cemu-bin-linux-x64
        path: ./bin/Cemu
        
  build-appimage:
    runs-on: ubuntu-22.04
    needs: build-ubuntu
    steps:
    - name: Checkout Upstream Repo
      uses: actions/checkout@v4
      with:
        repository: capitalistspz/Cemu
        ref: camera
        submodules: recursive
    - name: Checkout AppImage Repo
      uses: actions/checkout@v4
      with:
          clean: false
          path: ci
          
    - uses: actions/download-artifact@v4
      with:
        name: cemu-bin-linux-x64
        path: bin
                   
    - name: "Install system dependencies"
      run: |
        sudo apt update -qq
        sudo apt install -y clang-15 cmake freeglut3-dev libgcrypt20-dev libglm-dev libgtk-3-dev libpulse-dev libsecret-1-dev libsystemd-dev libudev-dev nasm ninja-build libbluetooth-dev appstream 

    - name: "Install openpnp-capture dependencies"
      run: |
        cd dependencies/openpnp-capture/
        cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -GNinja
        cmake --build build
        sudo ninja install -C build
        
    - name: "Build AppImage"
      run: |
        export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
        export DEPLOY_GTK_VERSION=3
        chmod +x dist/linux/appimage.sh && dist/linux/appimage.sh
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: cemu-appimage-x64
        path: artifacts
        
  #build-windows:
  #  runs-on: windows-2022
  #  env:
  #    install_vulkan_folder: "$GITHUB_WORKSPACE/vulkan_sdk"
  #    install_vulkan_version: "1.3.216.0"
  #  steps:
  #  - name: "Checkout repo"
  #    uses: actions/checkout@v4
  #    with:
  #      submodules: "recursive"
  #      
  #  - name: Setup release mode parameters (for deploy)
  #    if: ${{ inputs.deploymode == 'release' }}
  #    run: |
  #      echo "BUILD_MODE=release" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
  #      echo "BUILD_FLAGS=-DPUBLIC_RELEASE=ON" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
  #      echo "Build mode is release"
  #      
  #  - name: Setup debug mode parameters (for continous build)
  #    if: ${{ inputs.deploymode != 'release' }}
  #    run: |
  #      echo "BUILD_MODE=debug" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
  #      echo "BUILD_FLAGS=" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
  #      echo "Build mode is debug"
  #      
  #  - name: Prepare Vulkan SDK
  #    uses: humbletim/setup-vulkan-sdk@v1.2.0
  #    with:
  #      vulkan-query-version: 1.3.216.0
  #      vulkan-components: Vulkan-Headers, Vulkan-Loader
  #      vulkan-use-cache: false
  #  
  #  - name: Workaround
  #    run: |
  #      Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
  #      $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
  #      $componentsToRemove= @(
  #        "Microsoft.VisualStudio.Component.VC.14.32.17.2.ARM"
  #        "Microsoft.VisualStudio.Component.VC.14.32.17.2.ARM.Spectre"
  #        "Microsoft.VisualStudio.Component.VC.14.32.17.2.ARM64"
  #        "Microsoft.VisualStudio.Component.VC.14.32.17.2.ARM64.Spectre"
  #        "Microsoft.VisualStudio.Component.VC.14.32.17.2.x86.x64"
  #        "Microsoft.VisualStudio.Component.VC.14.32.17.2.x86.x64.Spectre"
  #        "Microsoft.VisualStudio.Component.VC.14.32.17.2.ATL"
  #        "Microsoft.VisualStudio.Component.VC.14.32.17.2.ATL.Spectre"
  #        "Microsoft.VisualStudio.Component.VC.14.32.17.2.ATL.ARM"
  #        "Microsoft.VisualStudio.Component.VC.14.32.17.2.ATL.ARM.Spectre"
  #        "Microsoft.VisualStudio.Component.VC.14.32.17.2.ATL.ARM64"
  #        "Microsoft.VisualStudio.Component.VC.14.32.17.2.ATL.ARM64.Spectre"
  #        "Microsoft.VisualStudio.Component.VC.14.32.17.2.MFC"
  #        "Microsoft.VisualStudio.Component.VC.14.32.17.2.MFC.Spectre"
  #        "Microsoft.VisualStudio.Component.VC.14.32.17.2.MFC.ARM"
  #        "Microsoft.VisualStudio.Component.VC.14.32.17.2.MFC.ARM.Spectre"
  #        "Microsoft.VisualStudio.Component.VC.14.32.17.2.MFC.ARM64"
  #        "Microsoft.VisualStudio.Component.VC.14.32.17.2.MFC.ARM64.Spectre"
  #      )
  #      [string]$workloadArgs = $componentsToRemove | ForEach-Object {" --remove " +  $_}
  #      $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
  #      # should be run twice
  #      $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
  #      $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden#
  #
  #  - name: Configure MSVC
  #    uses: ilammy/msvc-dev-cmd@v1
  #    with:
  #      arch: amd64
  #      toolset: 14.33.31629
  #      spectre: false
  #
  #  - name: "Bootstrap vcpkg"
  #    run: |
  #      ./dependencies/vcpkg/bootstrap-vcpkg.bat
  #      
  #  - name: 'Setup NuGet Credentials for vcpkg'
  #    shell: 'bash'
  #    run: |
  #      `./dependencies/vcpkg/vcpkg.exe fetch nuget | tail -n 1` \
  #      sources add \
  #      -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
  #      -storepasswordincleartext \
  #      -name "GitHub" \
  #      -username "${{ github.repository_owner }}" \
  #      -password "${{ secrets.GITHUB_TOKEN }}"
  #      `./dependencies/vcpkg/vcpkg.exe fetch nuget | tail -n 1` \
  #      setapikey "${{ secrets.GITHUB_TOKEN }}" \
  #      -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
  #      
  #  - name: "cmake"
  #    run: |
  #      mkdir -p build
  #      cd build
  #      cmake .. ${{ env.BUILD_FLAGS }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_MODE }}
  #      
  #  - name: "Build Cemu"
  #    run: |
  #      cd build
  #      cmake --build . --config ${{ env.BUILD_MODE }} -j 2
  #      
  #  - name: Upload artifact
  #    uses: actions/upload-artifact@v4
  #    if: ${{ inputs.deploymode == 'release' }}
  #    with:
  #      name: cemu-bin-windows-x64
  #      path: ./bin/Cemu.exe
