name: Build Cemu

on:
  push:
    paths-ignore:
      - "*.md"
  workflow_call:
    inputs:
      deploymode:
        required: false
        type: string

jobs:    
  build-appimage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Upstream Repo
      uses: actions/checkout@v3
      with:
        repository: cemu-project/Cemu
        ref: main
    - name: Checkout AppImage Repo
      uses: actions/checkout@v3
      with:
        repository: qurious-pixel/Cemu
        ref: ci-appimage
        clean: false
        path: ci

    - name: "Install system dependencies"
      run: |
        echo "Place Holder"

    - name: "Temp Fixes"
      run: |
        echo "Linux Fixes"
        cp ci/scripts/appimage.sh dist/linux/
        cp ci/scripts/cemu.png dist/linux/info.cemu.Cemu.png
        ls -al ci/scripts
            
    - name: "Build Cemu"
      run: |
          docker pull quriouspixel/cemu
          docker run -u root -v $(pwd):/Cemu -v "$HOME/.ccache":/root/.ccache quriouspixel/cemu /bin/bash ci/scripts/docker.sh

    - name: "Build AppImage"
      run: |
        ls -al
        
    #- name: Upload artifact
    #  uses: actions/upload-artifact@v3
    #  #if: ${{ inputs.deploymode == 'release' }}
    #  with:
    #    name: cemu-appimage-x64
    #    path: artifacts
