name: Build Cemu

on:
  push:

env:
  VCPKG_ROOT: "${{github.workspace}}/dependencies/vcpkg"
  VCPKG_BINARY_SOURCES: 'clear;nuget,GitHub,readwrite'

jobs:
  build-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        STDLIB: [libc++] # ,libstdc++]
    name: llvm ${{ matrix.STDLIB }}  
    runs-on: ubuntu-20.04
    env:
      CACHEDIR: "${{github.workspace}}/dependencies/linux_submodules"
      CC: clang-16
      CXX: clang++-16
      LLVM: -16
      VCPKG: OFF
    steps:
    - name: "Checkout repo"
      uses: actions/checkout@v3
      with:
        submodules: "recursive"
        fetch-depth: 0

    - name: cache
      uses: actions/cache@v3
      with:
        path: ${{ env.CACHEDIR }}
        key: build-${{ hashFiles('dist/linux/dependencies.sh') }}
        restore-keys: build-${{ hashFiles('dist/linux/dependencies.sh') }}

    - name: "Fetch full history for vcpkg submodule"
      run: |
        cd dependencies/vcpkg
        git fetch --unshallow
        git pull --all
      if: ${{ env.VCPKG == 'ON' }}
      
    - name: Setup release mode parameters (for deploy)
      run: |
        echo "BUILD_MODE=release" >> $GITHUB_ENV
        echo "BUILD_FLAGS=" >> $GITHUB_ENV
        echo "Build mode is release"

    - name: Setup version for experimental
      if: ${{ inputs.experimentalversion != '' }}
      run: |
        echo "[INFO] Experimental version ${{ inputs.experimentalversion }}"
        echo "BUILD_FLAGS=${{ env.BUILD_FLAGS }} -DEXPERIMENTAL_VERSION=${{ inputs.experimentalversion }}" >> $GITHUB_ENV

    - name: "Install system dependencies"
      run: | 
        CODENAME=$(lsb_release -c | awk '{ print $2 }')
        echo $CODENAME
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        curl -Lvs https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo add-apt-repository -y "deb http://apt.llvm.org/$CODENAME/ llvm-toolchain-$CODENAME$LLVM main"
        sudo apt update -qq
        sudo apt install -y ccache ninja-build cmake libgtk-3-dev libsecret-1-dev libgcrypt20-dev libsystemd-dev freeglut3-dev ${CC} nasm libpugixml-dev libcurl4-openssl-dev libglm-dev rapidjson-dev libzstd-dev libstdc++-11-dev libc++$LLVM-dev libc++abi$LLVM-dev lld appstream

    - name: "Install system submodules"
      run: | 
        chmod +x dist/linux/dependencies.sh
        dist/linux/dependencies.sh
      if: ${{ env.VCPKG == 'OFF' }}
      
    - name: "Bootstrap vcpkg"
      run: |
        bash ./dependencies/vcpkg/bootstrap-vcpkg.sh
      if: ${{ env.VCPKG == 'ON' }}
      
    - name: 'Setup NuGet Credentials for vcpkg'
      shell: 'bash'
      run: |
        mono `./dependencies/vcpkg/vcpkg fetch nuget | tail -n 1` \
        sources add \
        -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
        -storepasswordincleartext \
        -name "GitHub" \
        -username "${{ github.repository_owner }}" \
        -password "${{ secrets.GITHUB_TOKEN }}"
        mono `./dependencies/vcpkg/vcpkg fetch nuget | tail -n 1` \
        setapikey "${{ secrets.GITHUB_TOKEN }}" \
        -source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
      if: ${{ env.VCPKG == 'ON' }}
              
    - name: "cmake"
      run: |
        cmake -S . -B build ${{ env.BUILD_FLAGS }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_MODE }} \
        -DPORTABLE=OFF -DENABLE_VCPKG=${{ env.VCPKG }} -DCMAKE_CXX_FLAGS="-ldl -Wno-unused-command-line-argument -stdlib=${{ matrix.STDLIB }}" \
        -DCMAKE_C_COMPILER=/usr/bin/${{ env.CC }} -DCMAKE_CXX_COMPILER=/usr/bin/${{ env.CXX }} \
        -G Ninja -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_EXE_LINKER_FLAGS="-nodefaultlibs -lc++ -lc++abi -lm -lc -lgcc_s -lgcc"
        
    - name: "Build Cemu"
      run: |
        cmake --build build
        
    - name: Prepare artifact
      run: mv bin/Cemu_release bin/Cemu
              
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: cemu-bin-linux-x64
        path: ./bin/Cemu
        
    - name: "Build AppImage"
      run: |
        export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
        export DEPLOY_GTK_VERSION=3
        dist/linux/appimage.sh

    - name: Upload AppImage artifact
      uses: actions/upload-artifact@v3
      with:
        name: cemu-appimage-x64-${{ matrix.STDLIB }}
        path: artifacts

