name: Build Cemu

on:
  workflow_dispatch:
  push:

jobs:
  FreeBSD_Build:
    name: Cemu FreeBSD 
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      CCACHE_DIR: ${{ github.workspace }}/ccache
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          repository: kreinholz/Cemu-upstream # cemu-project/Cemu
          ref: main
          submodules: recursive
          fetch-depth: 0

      - name: Restore Build Ccache
        uses: actions/cache/restore@main
        id: restore-build-ccache
        with:
          path: ${{ env.CCACHE_DIR }}
          key: FreeBSD-ccache-${{github.run_id}}
          restore-keys: FreeBSD-ccache-

      - name: FreeBSD build
        id: root
        uses: vmactions/freebsd-vm@v1
        with:
          envs: 'CCACHE_DIR'
          usesh: true
          run: chmod +x .github/workflows/freebsd_build.sh && .github/workflows/freebsd_build.sh

      - name: Save Build Ccache
        if: github.ref == 'refs/heads/master'
        uses: actions/cache/save@main
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ steps.restore-build-ccache.outputs.cache-primary-key }}

