name: Build Cemu

on:
  workflow_call:
  push:

jobs:
  build-fedora:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: "recursive"
        fetch-depth: 0

    - name: Docker setup and build
      run: |
          chmod +x .github/linux_arm64_build.sh
          docker pull --quiet rpcs3/rpcs3-ci-jammy-aarch64:1.6
          docker run \
            -v $PWD:/cemu \
            rpcs3/rpcs3-ci-jammy-aarch64:1.6 \
            .github/linux_arm64_build.sh
         
   # - name: Upload artifact
   #   uses: actions/upload-artifact@v4
   #   with:
   #     name: cemu-bin-linux-x64
   #     path: ./bin/Cemu

  #build-appimage:
  #  runs-on: ubuntu-22.04
  #  needs: build-ubuntu
  #  steps:
  #  - name: Checkout Upstream Repo
  #    uses: actions/checkout@v4

  #  - uses: actions/download-artifact@v4
  #    with:
  #      name: cemu-bin-linux-x64
  #      path: bin

  # - name: "Install system dependencies"
  #    run: |
  #      sudo apt update -qq
  #      sudo apt install -y clang-15 cmake freeglut3-dev libgcrypt20-dev libglm-dev libgtk-3-dev libpulse-dev libsecret-1-dev libsystemd-dev nasm ninja-build appstream libbluetooth-dev

  # - name: "Build AppImage"
  #  run: |
  #      export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
  #      export DEPLOY_GTK_VERSION=3
  #      dist/linux/appimage.sh

  # - name: Upload artifact
  #   uses: actions/upload-artifact@v4
  #   with:
  #     name: cemu-appimage-x64
  #     path: artifacts


